login: &login
  adapter: postgresql
  host: localhost
  username: zaglohla
  password: b9ddadb9
  template: template0
  encoding: utf8
  port: 5432
  pool: 50

development:
  <<: *login
  database: zaglohla_production

production:
  <<: *login
  database: zaglohla_production

test: &test
  <<: *login
  database: zaglohla_test
  min_messages: WARNING
